/******************************************************************************/
/*!
\file	FollowSpline.cs
\author Ng Tian Kiat
\par	email: tiankiat.ng\@digipen.edu
\details
	This script moves a gameobject along a series of waypoints generated by a spline,
    script (Catmullrom).

\copyright	Copyright (c) 2021 DigiPen Institute of Technology. Reproduction
			or disclosure of this file or its contents without the prior
			written consent of DigiPen Institute of Technology is prohibited.
*/
/******************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Scripting
{
    public abstract class MonoBehaviour
    {
        public uint entityID;

        public abstract void Init(ref uint _entityID);
        public abstract void Start();
        public abstract void Update(ref Transform transform, ref Rigidbody rigidbody, ref float dt);
        public abstract void LateUpdate(ref Transform transform, ref Rigidbody rigidbody, ref float dt);
    }
}
