#pragma once

#include <string>
#include <unordered_map>

namespace Pogplant
{
	struct UsedTex
	{
		bool m_Used;
		// ID that was generated by opengl
		unsigned int m_ID;
		// Array index
		unsigned int m_MappedID;
	};

	struct TextureResource
	{
		static void InitResource();
		static void ReloadTextures();
		//static void UseTexture(std::string _TexName);
		//static int GetUsedTextureID(std::string _TexName);
		static std::unordered_map<std::string, unsigned int> m_TexturePool;
		static std::unordered_map<std::string, UsedTex> m_UsedTextures;
		// If used textures need to be updated
		static bool m_Updated;
		static unsigned int m_UsedTexCount;
	};
}